name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - actions-test
    tags:
      - "v*"

jobs:
  # ----------------------------
  # Build Linux Binary
  # ----------------------------
# Linux is commented out for now as the game itself can only run on windows
#  build-linux:
#    name: Build (Linux)
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install Rust
#        uses: dtolnay/rust-toolchain@stable
#
#      - name: Build release binary
#        run: cargo build --release --target x86_64-unknown-linux-gnu
#
#      - name: Strip binary
#        run: strip target/x86_64-unknown-linux-gnu/release/gammaeditor
#
#      - name: Upload Linux binary
#        uses: actions/upload-artifact@v4
#        with:
#          name: gammaeditor-linux
#          path: target/x86_64-unknown-linux-gnu/release/gammaeditor

  # ----------------------------
  # Build Windows Binary
  # ----------------------------
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare artifact folder
        run: |
          mkdir dist
          mkdir dist\GammaEditor
          mkdir dist\GammaEditor\logs
          copy target\x86_64-pc-windows-msvc\release\gammaeditor.exe dist\GammaEditor\gammaeditor.exe


      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: gammaeditor-windows
          path: dist/GammaEditor/

  # ----------------------------
  # Package Source Code
  # ----------------------------
  package-source:
    name: Package Source Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create source archive
        run: |
          mkdir -p dist
          zip -r "dist/Source code.zip" . -x "target/*" ".git/*" ".idea/*" ".vscode/*"

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: "Source code"
          path: "dist/Source code.zip"